const mockData = [
    {
        id: 1,
        marca: 'Toyota',
        modelo: 'Corolla',
        tipo: 'Sedan',
        precio: '$20,000',
    },
    {
        id: 2,
        marca: 'Ford',
        modelo: 'Mustang',
        tipo: 'Coupe',
        precio: '$35,000',
    },
    {
        id: 3,
        marca: 'Chevrolet',
        modelo: 'Camaro',
        tipo: 'Coupe',
        precio: '$37,000',
    },
    {
        id: 4,
        marca: 'Honda',
        modelo: 'Civic',
        tipo: 'Sedan',
        precio: '$22,000',
    },
    {
        id: 5,
        marca: 'BMW',
        modelo: 'X5',
        tipo: 'SUV',
        precio: '$50,000',
    },
    // Agrega más vehículos según sea necesario...
    {
        id: 6,
        marca: 'Mercedes',
        modelo: 'C-Class',
        tipo: 'Sedan',
        precio: '$45,000',
    },
    {
        id: 7,
        marca: 'Audi',
        modelo: 'A4',
        tipo: 'Sedan',
        precio: '$42,000',
    },
    {
        id: 8,
        marca: 'Nissan',
        modelo: 'Altima',
        tipo: 'Sedan',
        precio: '$24,000',
    },
    {
        id: 9,
        marca: 'Tesla',
        modelo: 'Model S',
        tipo: 'Sedan',
        precio: '$80,000',
    },
    {
        id: 10,
        marca: 'Jeep',
        modelo: 'Wrangler',
        tipo: 'SUV',
        precio: '$35,000',
    },
    {
        id: 11,
        marca: 'Subaru',
        modelo: 'Outback',
        tipo: 'SUV',
        precio: '$28,000',
    },
    {
        id: 12,
        marca: 'Mazda',
        modelo: 'CX-5',
        tipo: 'SUV',
        precio: '$26,000',
    },
    {
        id: 13,
        marca: 'Hyundai',
        modelo: 'Elantra',
        tipo: 'Sedan',
        precio: '$21,000',
    },
    {
        id: 14,
        marca: 'Kia',
        modelo: 'Sorento',
        tipo: 'SUV',
        precio: '$30,000',
    },
    {
        id: 15,
        marca: 'Volkswagen',
        modelo: 'Passat',
        tipo: 'Sedan',
        precio: '$25,000',
    },
    {
        id: 16,
        marca: 'Lexus',
        modelo: 'RX',
        tipo: 'SUV',
        precio: '$48,000',
    },
    {
        id: 17,
        marca: 'Dodge',
        modelo: 'Charger',
        tipo: 'Sedan',
        precio: '$33,000',
    },
    {
        id: 18,
        marca: 'Toyota',
        modelo: 'RAV4',
        tipo: 'SUV',
        precio: '$29,000',
    },
    {
        id: 19,
        marca: 'Ford',
        modelo: 'Explorer',
        tipo: 'SUV',
        precio: '$36,000',
    },
    {
        id: 20,
        marca: 'Chevrolet',
        modelo: 'Tahoe',
        tipo: 'SUV',
        precio: '$49,000',
    },
];

export default mockData